export const CHAT_LIST_FAIL = 'CHAT_LIST_FAIL'
export const CHAT_LIST_SUCCESS = 'CHAT_LIST_SUCCESS'
export const CHAT_LIST_LOADING = 'CHAT_LIST_LOADING'

export const MESSAGE_LIST_FAIL = 'MESSAGE_LIST_FAIL'
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS'
export const MESSAGE_LIST_LOADING = 'MESSAGE_LIST_LOADING'
